### PR TITLE
[R1340] Term count fix

### PR DESCRIPTION
**Pull request by psiotwo**

### CODE REVIEW

**Review by blcham — COMMENTED** [review]
Well, this might only work if you put termit-model and termit-glosar into default context, which is not case in any deployments that I did in last 2 weeks. If it should be done like this:
- README.md should change -- i am not sure where to look now.
-  it is correct although I liked termit-model and termit-glosar to be in separated context as it can be easily removed (but no big deal).

**Comment by psiotwo** [comment]
> Well, this might only work if you put termit-model and termit-glosar into default context, which is not case in any deployments that I did in last 2 weeks. If it should be done like this:
> 
> * README.md should change -- i am not sure where to look now.
> * it is correct although I liked termit-model and termit-glosar to be in separated context as it can be easily removed (but no big deal).

It works on CSAT, so I checked why - there does not seem to be an artifact for termit-slovník (only glosář and model). On the contrary, the managed vocabularies do have it. So it seems it is enough for now.

Another option would be to explicitely remove terms which are in termit glossary.

And yet another option would be to equip all our "system vocabularies" with a special flag

**Comment by blcham** [comment]
Yes, it is sufficient for now.  The flag seems to me the best options as it could be used to hide some other vocabularies as well such as SGOV. SGOV is most-likely not useful to have in the termit deployment for some organization, but it is good to have it there as "system vocabulary" (as it provides at least labels for types).

**Review by blcham — APPROVED** [review]
I have already provided reason to approve in comments.

**Pull request merged**
