### PR TITLE
1445 bug multilingual changes display

### PR DESCRIPTION
**Pull request by ledsoft**
Frontend for https://kbss.felk.cvut.cz/redmine/issues/1445

### CODE REVIEW

**Review by psiotwo — COMMENTED** [review]
tests look good, but I cannot see it in the preview. Maybe I am looking at some wrong place:
https://deploy-preview-58--termit-dev.netlify.app/#/vocabularies/pokusny-dokumentovy-slovnik/terms/aadam?namespace=http://onto.fel.cvut.cz/ontologies/slovnik/&includeImported=false

**Comment by psiotwo** [comment]
> tests look good, but I cannot see it in the preview. Maybe I am looking at some wrong place:
> https://deploy-preview-58--termit-dev.netlify.app/#/vocabularies/pokusny-dokumentovy-slovnik/terms/aadam?namespace=http://onto.fel.cvut.cz/ontologies/slovnik/&includeImported=false

Ah I see, maybe I need the backend as well ...

**Comment by ledsoft** [comment]
Yes, you need the backend to provide multilingual values. I should have probably mentioned that. Sorry...

**Comment by psiotwo** [comment]
> Yes, you need the backend to provide multilingual values. I should have probably mentioned that. Sorry...

LGTM, here is a proposal for a different visualization:
https://github.com/kbss-cvut/termit-ui/pull/59

**Review by psiotwo — APPROVED** [review]
see comment

**Pull request merged**
