### PR TITLE
1419 skos import

### PR DESCRIPTION
**Pull request by psiotwo**
- [R-#1419](https://kbss.felk.cvut.cz/redmine/issues/1419)

### CODE REVIEW

**Comment by MichalMed** [comment]
after importing skos, i get unspecified red error in upper right corner and get redirected to vocabularies list

**Comment by psiotwo** [comment]
@MichalMed backend deployed to dev.

**Comment by MichalMed** [comment]
na devu nic není

**Review by MichalMed — CHANGES_REQUESTED** [review]
Vocabulary may be imported. After uploading the file and pressing import, I get the message that everything went well, but I:
1) do not know the name of the vocabulary,
2) can not find it in the vocabularies list,
3) can not find terms from the "imported" vocabulary in TermIt.

Basically I suspect the system that it only tells me it is OK, but actually nothing happened.

**Review by MichalMed — APPROVED** [review]
lgtm

**Pull request merged**
