### PR TITLE
[Task #1520] Add a link to the tutorial to annotator actions.

### LINKED ISSUE #170: Nápověda pro anotátor
# Popis
Jako editor slovníku, který poprvé používá anotátor,
potřebuji použít nápovědu v anotátoru,
která mě navede, jak s anotátorem pracovat, a podrobněji mi vysvětlí pojmy v legendě.

# Možné řešení
Využít tooltip nápovědy, jak je naznačeno symbolem otazníku na obrázku. Pod větším (hlavním) otazníkem nahoře by se mohla skrývat "hlavní" nápověda - něco ve smyslu začněte označením textu v dokumentu...

image

# Užitečnost
Popište, jak užitečná Vám funkce přijde
3. bylo by hezké ji mít, ale bez problémů se bez ní obejdu

### PR DESCRIPTION
**Pull request by ledsoft**
https://kbss.felk.cvut.cz/redmine/issues/1520 - tutorial link

### CODE REVIEW

**Review by psiotwo — CHANGES_REQUESTED** [review]
works ok, but the user is not warned that he is navigating outside the app (contrary to the other buttons in the toolbar). Would be good to have there e.g. the outgoing link icon/tooltip to inform the user upfront.

**Comment by ledsoft** [comment]
Ok, but If I put there the outgoing link icon, it looks weird, since it goes to the right of the label, whereas the analysis button has an icon on the left. And if I put it to the left, it will be inconsistent with how external links behave throughout the application...

**Comment by psiotwo** [comment]
> Ok, but If I put there the outgoing link icon, it looks weird, since it goes to the right of the label, whereas the analysis button has an icon on the left. And if I put it to the left, it will be inconsistent with how external links behave throughout the application...

A suggestion: not to have a separate button, but an outgoing link only, so that:
- the show/hide legend button becomes "Help" (e.g. with the (i) icon)
- there will be an outgoing link in the legend saying "See how to work with annotator.", rendered as hyperlink

Or the hyperlink-rendered outgoing link having in the button toolbar directly.

**Comment by ledsoft** [comment]
Ok, reworked according to feedback.

**Review by psiotwo — APPROVED** [review]
lgtm

**Pull request merged**
