### PR TITLE
1347 multilingual attribute editing

### PR DESCRIPTION
**Pull request by ledsoft**
https://kbss.felk.cvut.cz/redmine/issues/1347 - allow removal of translation in term.

### CODE REVIEW

**Review by psiotwo — COMMENTED** [review]
Removing Czech language ends up with 
image


https://deploy-preview-31--termit-dev.netlify.app/#/vocabularies/pokusny-dokumentovy-slovnik/terms/bbedrich?namespace=http://onto.fel.cvut.cz/ontologies/slovnik/&includeImported=false

**Comment by ledsoft** [comment]
Fixed

**Review by psiotwo — COMMENTED** [review]
Language removal works, but I am not able to test it fully, as saving the updated resource does not work

I am getting "Text analysis invocation failed." without having changes persisted.

**Comment by ledsoft** [comment]
The problem with failed text analysis is apparently due to the conflict between frotend on Netlify, which uses github version with multilingual strings and backend on KBSS, which is from development branch and does not use multilingual strings yet.

**Comment by ledsoft** [comment]
Correction: the problem is that the text analysis service uses language configured in server deployment (cs in our case), but if you don't provide definition in that language, annotace fails, because its input is null. I think annotace should be able to handle empty input for analysis.

**Review by psiotwo — APPROVED** [review]
tested, lgtm

**Review by psiotwo — APPROVED** [review]

**Pull request merged**
